#include <stdio.h>
#define HUGS_SERVER 1
#include "prelude.h"
#include "storage.h"
#include "connect.h"
#include "machdep.h"
#include "observe.h"
#include "server.h"
#include "prelude.h"
#include "storage.h"
#include "connect.h"
#include "script.h"
#include "machdep.h"
#include "evaluator.h"
#include "opts.h"
#include "strutil.h"
#include "errors.h"
#include "server.h"

#include <setjmp.h>

#define BEGIN_PROTECT \
  if (NULL == lastError) { \
      Cell dummy; \
      CStackBase = &dummy;              /* Save stack base for use in gc  */ \
      consGC = TRUE;                    /* conservative GC is the default */ \
      if (!setjmp(catch_error)) {
#define END_PROTECT \
      } else { \
    fprintf(stderr, "END_PROTECT_CALLED\n"); \
    setError("Error occurred"); \
    normalTerminal(); \
      } \
  }


// WTF is WASM complaining about?!
// error: undefined symbol: __secs_to_tm

static int check(int lineno, HugsServerAPI hugs, char *out) {
    char* err = hugs.clearError();
    if (err) {
        sprintf(out,"%s::%s | runhugs error: %s\n", __FILE__, __FUNCTION__, err);
        return 1;
    } 
    return 0;
}

static char *hugs_argv[] = {"runhugs"};
static int hugs_argc = sizeof hugs_argv / sizeof hugs_argv[0];
 

void get_output(char *in, char *out) {
    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
    HugsServerAPI hugs;
    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);

    setHugsAPI(&hugs);
  
    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);

    BEGIN_PROTECT           /* Too much text for protect()     */
    Int i;

    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
    startEvaluator();
    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
    readOptionSettings();
    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);

    EnableOutput(FALSE);
    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
    const int USE_MEMORY_PRELUDE = 0;
    if (USE_MEMORY_PRELUDE) {
        printf("=> LOADING **IN-MEMORY** PRELUDE | FILE (%s) LINE (%d)\n", __FILE__, __LINE__);
        // loadAutogeneratedPrelude();
        loadNoImplicitPrelude();
    } else {
        printf("=> LOADING **FILESYSTEM** PRELUDE | FILE(%s) LINE (%d)\n", __FILE__, __LINE__);
        loadPrelude();
    }
    if (check(__LINE__, hugs, out)) { return; }

    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);

    if (USE_MEMORY_PRELUDE) {}
    else { addScriptName("Hugs.Dynamic",TRUE); }
    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
    if (check(__LINE__, hugs, out)) { return; }
    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
    if (USE_MEMORY_PRELUDE) {
        readScriptsAutogeneratedPrelude();
    } else { 
        readScripts(0);
    }
    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
    everybody(RESET);
    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
    
    if (!linkDynamic()) { setError("module HugsDynamic doesn't define correct functions");}

    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
    if (check(__LINE__, hugs, out)) { return; }

    END_PROTECT
    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);

    if (check(__LINE__, hugs, out)) { return; }
    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
    hugs.setOutputEnable(0);
    // defined in iomonad.c
    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
    hugs.setHugsArgs(hugs_argc, hugs_argv);
    if (check(__LINE__, hugs, out)) { return; }

    int exitCode = 42;
    if (1) {
        printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
        // hugs.loadFile("test-wasm-main.hs");
        hugs.loadFromBuffer(in);
        printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
        hugs.lookupName("Main","main");
        printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
        if(check(__LINE__, hugs, out)) { return; }

        printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
        exitCode = hugs.doIO();
        printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
        if(check(__LINE__, hugs, out)) { return; }
    }
    else {
        printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
        // hugs->pushHVal(hugs->compileExpr("Main", in));
        hugs.pushHVal(hugs.compileExpr("Main","putStrLn \"foo\""));
        if(check(__LINE__, hugs, out)) { return; }
        printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
        exitCode = hugs.doIO();
        printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
        if(check(__LINE__, hugs, out)) { return; }
    }

    printf("ran till FILE(%s) LINE(%d)\n", __FILE__, __LINE__);
    shutdownHugsServer(&hugs);
    assert(exitCode != 42);
    exit(exitCode);
}


int main() {
    printf("hello, world\n");

    char in[4096], out[4096];
    strcpy(in,  "module Main where main = putStrLn \"hello foo\" ");
    get_output(in, out);
    printf("output:\n%s\n", out);
    return 0;
}
